# Generated by Django 6.0.2 on 2026-02-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='idade_maio',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lista',
            name='idade_menor',
            field=models.CharField(blank=True, null=True),
        ),
    ]
